//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staffing.data.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_title
    {
        public int job_title_id { get; set; }
        public string job_title_name { get; set; }
        public bool is_active { get; set; }
    }
}
