//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staffing.data.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class logging
    {
        public int exception_id { get; set; }
        public string exception_message { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
        public string exception_stack_trace { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
        public string user_ip { get; set; }
        public int user_id { get; set; }
    }
}
