//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staffing.data.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_status
    {
        public int position_status_id { get; set; }
        public string position_status_name { get; set; }
        public bool is_active { get; set; }
    }
}
