//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace staffing.data.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffing
    {
        public int staffing_id { get; set; }
        public int job_title_id { get; set; }
        public bool epic_position { get; set; }
        public int total_no_of_positions { get; set; }
        public int no_of_positions_filled { get; set; }
        public Nullable<int> job_location_id { get; set; }
        public Nullable<System.DateTime> date_job_received { get; set; }
        public Nullable<int> client_id { get; set; }
        public string job_description { get; set; }
        public Nullable<int> assigned_to_whom_id { get; set; }
        public Nullable<int> account_manager_id { get; set; }
        public Nullable<int> position_status_id { get; set; }
        public string follow_up_action { get; set; }
        public Nullable<int> position_type_id { get; set; }
        public string rate_range_w2 { get; set; }
        public string rate_range_c2c_1099 { get; set; }
        public string duration { get; set; }
        public bool t_e_paid { get; set; }
        public bool is_active { get; set; }
        public Nullable<int> created_by_user_id { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<int> last_updated_by_user_id { get; set; }
        public Nullable<System.DateTime> last_updated_datetime { get; set; }
        public Nullable<System.DateTime> job_closed_date { get; set; }
        public Nullable<int> client_manager_id { get; set; }
    }
}
